name: Docker.

on:
  push:
    paths:
      - '.github/workflows/docker.yml'
      - 'Telegram/build/docker/centos_env/**'
  pull_request:
    paths:
      - '.github/workflows/docker.yml'
      - 'Telegram/build/docker/centos_env/**'

jobs:
  docker:
    name: Ubuntu
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ghcr.io/${{ github.repository }}/centos_env:latest

    steps:
      - name: Clone.
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: First set up.
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Docker image build.
        run: |
          cd Telegram/build/docker/centos_env
          poetry install
          DEBUG= poetry run gen_dockerfile | docker buildx build -t $IMAGE_TAG -
      
      - name: Push the Docker image.
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push $IMAGE_TAG
